mertboiifpv/Controllers/CetusDronesController.cs
using mertboiifpv.Data;
using mertboiifpv.Data.Services;
using mertboiifpv.Models.Drones;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace mertboiifpv.Controllers
{
    public class CetusDronesController : Controller
    {

        private readonly ICetusDronesService _service;

        public CetusDronesController(ICetusDronesService service)
        {
            _service = service;
        }


        public async Task<IActionResult> Index()
        {


            var data = await _service.GetAllAsync();
            return View("~/Views/Drones/Cetus/Index.cshtml", data);


        }





        //Get: Cinemas/Details/1
        public async Task<IActionResult> Details(int id)
        {
            var data = await _service.GetByIdAsync(id);
            if (data == null) return View("NotFound");
            return View("~/Views/Drones/Cetus/Details.cshtml", data);
        }

        //GET: Movies/Create
        public IActionResult Create()
        {


            return View("~/Views/Drones/Cetus/Create.cshtml");
        }

        [HttpPost]
        public async Task<IActionResult> Create(Cetus drone)
        {
            if (!ModelState.IsValid)
            {




                return View(drone);
            }

            await _service.AddNewCetusDroneAsync(drone);
            return RedirectToAction(nameof(Index));
        }
    }
}

mertboiifpv/Controllers/MainPageController.cs
using mertboiifpv.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace mertboiifpv.Controllers
{
    public class MainPageController : Controller
    {
        private readonly AppDbContext _context;

        public MainPageController(AppDbContext context)
        {
            _context = context;
        }
        public IActionResult Index()
        {
            //var allMeteorDrones = await _context.MeteorDrones.ToListAsync();
            return View();
        }
    }
}

mertboiifpv/Controllers/MeteorDronesController.cs
using mertboiifpv.Data;
using mertboiifpv.Data.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace mertboiifpv.Controllers
{
    public class MeteorDronesController : Controller
    {

        private readonly IMeteorDronesService _service;

        public MeteorDronesController(IMeteorDronesService service)
        {
            _service = service;
        }
        

        public async Task<IActionResult> Index()
        {
            

            var data = await _service.GetAllAsync();
            return View("~/Views/Drones/Meteor/Index.cshtml", data);

            
        }

        



        //Get: Cinemas/Details/1
        public async Task<IActionResult> Details(int id)
        {
            var data = await _service.GetByIdAsync(id);
            if (data == null) return View("NotFound");
            return View("~/Views/Drones/Meteor/Details.cshtml", data);
        }

        //Get: Cinemas/Details/1
        


    }
}

mertboiifpv/Controllers/PavoDronesController.cs
using mertboiifpv.Data;
using mertboiifpv.Data.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace mertboiifpv.Controllers
{
    public class PavoDronesController : Controller
    {
        private readonly IPavoDronesService _service;

        public PavoDronesController(IPavoDronesService service)
        {
            _service = service;
        }


        public async Task<IActionResult> Index()
        {


            var data = await _service.GetAllAsync();
            return View("~/Views/Drones/Pavo/Index.cshtml", data);


        }

        //Get: Cinemas/Details/1
        public async Task<IActionResult> Details(int id)
        {
            var data = await _service.GetByIdAsync(id);
            if (data == null) return View("NotFound");
            return View("~/Views/Drones/Pavo/Details.cshtml", data);
        }
    }
}

mertboiifpv/Views/MainPage/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}



<div id="carouselExampleIndicators" class="carousel slide bg-danger" data-ride="carousel ">

    <div class="carousel-inner" style=" font-family: 'Sebino-Regular ☞';">
        <div class="carousel-item active">
            <a asp-controller="CetusDrones" asp-action="Index"><img class="d-block w-100" src="https://cdn.shopify.com/s/files/1/1778/6615/files/slide_a6670339-4775-4359-abcf-f32159ab1ede_2160x.jpg?v=1669723533" alt="First slide"></a>
            <div style="font-weight:600" class="carousel-caption d-none d-md-block">
                <p style="font-size:25px;">Cetus Pro FPV Kit</p>

            </div>
        </div>
        <div class="carousel-item">
            <a asp-controller="PavoDrones" asp-action="Index"><img class="d-block w-100" src="https://cdn.shopify.com/s/files/1/1778/6615/files/Slide1_bb13be3c-28f4-4756-8242-b5e37c0057b5_2160x.jpg?v=1656067676" alt="Third slide"></a>
            <div style="font-weight:600" class="carousel-caption d-none d-md-block">
                <p style="font-size:25px;">Pawo25 Whoop Quadcopter</p>

            </div>
        </div>

        <div class="carousel-item">
            <a asp-controller="MeteorDrones" asp-action="Index"><img class="d-block w-100" src="https://cdn.shopify.com/s/files/1/1778/6615/files/Slide_1_a8f15b41-c35d-40bc-9738-a0bb6ab6d0fa_2160x.jpg?v=1662718930" alt="Third slide"></a>  
            <div style="font-weight:600" class="carousel-caption d-none d-md-block">
                <p style="font-size:25px;">Meteor75 HD Brushless Whoop Quadcopter</p>

            </div>
        </div>
    </div>
    <ol class="carousel-indicators">
        <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
    </ol>
    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>




<br />



<div class="container-fluid ">
    <div class="row">

        <div class="col-md-4">
            <img class="img-fluid" src="https://cdn.shopify.com/s/files/1/1778/6615/files/NEW3_6b6b9826-51d1-440d-908b-9459d397bdce_540x.jpg?v=1665732210" />

            <div style="text-align:center">
                <a style="font-family: 'Sebino-Regular ☞'; color: black " href="#" class="text-decoration-none text-muted">Cetus X FPV Kit</a>
            </div>
        </div>
        <div class="col-md-4">
            <img class="img-fluid" src="https://cdn.shopify.com/s/files/1/1778/6615/files/Newest_2_61586b1f-743b-41ad-b4c9-305dc9eec433_540x.jpg?v=1656067327" />
            <div style="text-align:center">
                <a style=" font-family: 'Sebino-Regular ☞'; color: black " href="#" class="text-decoration-none text-muted">Pawo 25 Whoop Quadcopter</a>
            </div>
        </div>
        <div class="col-md-4">
            <img class="img-fluid" src="https://cdn.shopify.com/s/files/1/1778/6615/files/New1_1119a45d-33ef-466d-8e41-3be82ada6bc9_540x.jpg?v=1668162319" />
            <div style="text-align:center">
                <a style=" font-family: 'Sebino-Regular ☞'; color: black " href="#" class="text-decoration-none text-muted">Meteor Series Whoop Drones</a>
            </div>
        </div>

    </div>
</div>